resources:
  - front-end/frontend.yaml
  - back-end/backend.yaml
  - front-end/ingress.yaml

configMapGenerator:
  - name: next-frontend-config #fix me
    files:
      - config.json=config/frontend-config.json
  - name: java-backend-config #fix me
    files:
      - config.json=config/backend-config.json

generatorOptions:
  disableNameSuffixHash: true